In [16]:
# employee data with key as id of the employee and values as age of the employee
Employee_data ={101: 43, 102: 25, 103: 43, 104: 31, 105: 26, 106: 28, 107: 29, 108: 43, 109: 25, 110: 22, 111: 22, 112: 25, 113: 30, 115: 45, 116: 23, 117: 29, 118: 28, 119: 30, 120: 28, 121: 42, 122: 39, 123: 29, 124: 42, 125: 43, 126: 42, 127: 40, 128: 27, 129: 23, 130: 30, 131: 37, 132: 20, 133: 36, 134: 27, 135: 27, 136: 22, 137: 28, 138: 23, 139: 45, 140: 39, 141: 29, 142: 33, 143: 39, 145: 34, 146: 26, 147: 30, 148: 38, 149: 29, 150: 24, 151: 28, 152: 34, 153: 42, 154: 29, 155: 23, 156: 31, 158: 25, 160: 45, 161: 42, 162: 27, 163: 24, 164: 20, 166: 24, 167: 28, 168: 20, 169: 33, 170: 34, 171: 37, 172: 45, 173: 35, 174: 23, 175: 44, 176: 27, 177: 30, 178: 26, 179: 27} 

#### Identify the senior most employees age

- 45
- 44
- 48
- 42

In [12]:
# Type your code here
Key_max = max(Employee_data.values())
print(Key_max)

45


#### Identify the age of the employee with employee id 159 [ If the employee isn't present return NA]

- 25
- 32
- NA
- 42

In [17]:
# Type your code here
Employee_data[159]

KeyError: 159

#### Count the total number of employee in the organization

- 79
- 78
- 60
- 74

In [18]:
# Type your code here
len(Employee_data)

74

#### Calculate the mean age of the employees

- 31.36
- 36.48
- 28.77
- 32.47

In [26]:

# printing original dictionary 
print("The original dictionary is : " + str(Employee_data)) 
  
# loop to sum all values  
res = 0
for val in Employee_data.values(): 
    res += val 
  
# using len() to get total keys for mean computation 
res = res / len(Employee_data) 
  
# printing result  
print("The computed mean : " + str(res))  

The original dictionary is : {101: 43, 102: 25, 103: 43, 104: 31, 105: 26, 106: 28, 107: 29, 108: 43, 109: 25, 110: 22, 111: 22, 112: 25, 113: 30, 115: 45, 116: 23, 117: 29, 118: 28, 119: 30, 120: 28, 121: 42, 122: 39, 123: 29, 124: 42, 125: 43, 126: 42, 127: 40, 128: 27, 129: 23, 130: 30, 131: 37, 132: 20, 133: 36, 134: 27, 135: 27, 136: 22, 137: 28, 138: 23, 139: 45, 140: 39, 141: 29, 142: 33, 143: 39, 145: 34, 146: 26, 147: 30, 148: 38, 149: 29, 150: 24, 151: 28, 152: 34, 153: 42, 154: 29, 155: 23, 156: 31, 158: 25, 160: 45, 161: 42, 162: 27, 163: 24, 164: 20, 166: 24, 167: 28, 168: 20, 169: 33, 170: 34, 171: 37, 172: 45, 173: 35, 174: 23, 175: 44, 176: 27, 177: 30, 178: 26, 179: 27}
The computed mean : 31.364864864864863


#### Perform the following two tasks and then calculate the updated mean age of the employees
Task1 Update the ages of employee id - 104,140, and 164 as 27 <br>
Task2 Remove the employ with employee id - 143 <br>

- 30.71
- 31.36
- 30.13
- 31.13


In [29]:
# Type your code here
Employee_data[104]=27
Employee_data[140]=27
Employee_data[164]=27
del Employee_data[143]

In [30]:
print("The original dictionary is : " + str(Employee_data)) 
  
# loop to sum all values  
res = 0
for val in Employee_data.values(): 
    res += val 
  
# using len() to get total keys for mean computation 
res = res / len(Employee_data) 
  
# printing result  
print("The computed mean : " + str(res))  

The original dictionary is : {101: 43, 102: 25, 103: 43, 104: 27, 105: 26, 106: 28, 107: 29, 108: 43, 109: 25, 110: 22, 111: 22, 112: 25, 113: 30, 115: 45, 116: 23, 117: 29, 118: 28, 119: 30, 120: 28, 121: 42, 122: 39, 123: 29, 124: 42, 125: 43, 126: 42, 127: 40, 128: 27, 129: 23, 130: 30, 131: 37, 132: 20, 133: 36, 134: 27, 135: 27, 136: 22, 137: 28, 138: 23, 139: 45, 140: 27, 141: 29, 142: 33, 145: 34, 146: 26, 147: 30, 148: 38, 149: 29, 150: 24, 151: 28, 152: 34, 153: 42, 154: 29, 155: 23, 156: 31, 158: 25, 160: 45, 161: 42, 162: 27, 163: 24, 164: 27, 166: 24, 167: 28, 168: 20, 169: 33, 170: 34, 171: 37, 172: 45, 173: 35, 174: 23, 175: 44, 176: 27, 177: 30, 178: 26, 179: 27}
The computed mean : 31.136986301369863


In [31]:
s = 'a$b@c@d'
print(s.split('@','$'))

TypeError: 'str' object cannot be interpreted as an integer

In [32]:
list_1 = ['red' , 'orange', 'blue', 'green', 'black', 'white']
print(list_1.sort())

None


In [33]:
num_1=[9,4,2,7]
num_2=[8,3,6,1]
print(sorted(num_1))
print(num_1)
print(num_2.sort())
print(num_2)

[2, 4, 7, 9]
[9, 4, 2, 7]
None
[1, 3, 6, 8]


In [34]:
l = ['paris','india','china','london']
print(tuple(l+['sri lanka']))

('paris', 'india', 'china', 'london', 'sri lanka')


In [35]:
var=(5)
print(type(var))

<class 'int'>


In [36]:
tup=([1,3,5],"abcd",(2,4),6)
tup[0][2]=7
print(tup)

([1, 3, 7], 'abcd', (2, 4), 6)


In [37]:
a= {1,2,4,5}
b= {5,6,7,8}
print(a-b)

{1, 2, 4}


In [38]:
s= {3,4,5}
s*2


TypeError: unsupported operand type(s) for *: 'set' and 'int'

In [39]:
numbers= {1,0,6,1,4,0,7}
print(len(numbers))


5


In [40]:
dict= {'ab':12,'cd':34,'ef':56}
print(dict[1])

KeyError: 1

In [41]:
marks= {'John':45,'Alex':60}
print(marks.keys())

dict_keys(['John', 'Alex'])


In [42]:
d = {"Python":40, "R":45}
"Python" in d

True

In [43]:
input_str="I love programming in python"
count=0
l=['a','e','i','o','u']
for i in input_str.lower():
  if i in l:
  	count=count+1
print(count)


8


In [44]:
l=[11, 13, 101, 14, 33, 141, 12, 144, 54, 67, 8, 11]
print(sum(l))

609


In [46]:
input_list = ast.literal_eval(input())

if (len(input_list)) <= 11:
    print(sum(input_list))
else:
    print(-1)

NameError: name 'ast' is not defined